# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sparkie_board_connect.protos.nanopb_pb2 as nanopb__pb2
import sparkie_board_connect.protos.imu_pb2 as imu__pb2
import sparkie_board_connect.protos.ultrasonic_pb2 as ultrasonic__pb2
import sparkie_board_connect.protos.ledstrip_pb2 as ledstrip__pb2
import sparkie_board_connect.protos.motors_pb2 as motors__pb2
import sparkie_board_connect.protos.servo_pb2 as servo__pb2
import sparkie_board_connect.protos.aht_pb2 as aht__pb2
import sparkie_board_connect.protos.airq_pb2 as airq__pb2
import sparkie_board_connect.protos.battery_pb2 as battery__pb2
import sparkie_board_connect.protos.odometry_pb2 as odometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\x1a\x0cnanopb.proto\x1a\timu.proto\x1a\x10ultrasonic.proto\x1a\x0eledstrip.proto\x1a\x0cmotors.proto\x1a\x0bservo.proto\x1a\taht.proto\x1a\nairq.proto\x1a\rbattery.proto\x1a\x0eodometry.proto\"&\n\x08PingPong\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06isPing\x18\x02 \x01(\x08\"\x92\x04\n\x07Message\x12\x0f\n\x07topicId\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\r\x12\x1d\n\x08pingPong\x18\x03 \x01(\x0b\x32\t.PingPongH\x00\x12\x1b\n\x07imuData\x18\x04 \x01(\x0b\x32\x08.ImuDataH\x00\x12)\n\x0eultrasonicData\x18\x05 \x01(\x0b\x32\x0f.UltrasonicDataH\x00\x12%\n\x0cledstripData\x18\x06 \x01(\x0b\x32\r.LedstripDataH\x00\x12%\n\x0cmotorCommand\x18\x07 \x01(\x0b\x32\r.MotorCommandH\x00\x12#\n\x0bmotorStatus\x18\x08 \x01(\x0b\x32\x0c.MotorStatusH\x00\x12$\n\x0fmotorPidCommand\x18\r \x01(\x0b\x32\t.MotorPIDH\x00\x12%\n\x0cspeedCommand\x18\x0e \x01(\x0b\x32\r.SpeedCommandH\x00\x12\x1f\n\tservoData\x18\t \x01(\x0b\x32\n.ServoDataH\x00\x12\x1b\n\x07\x61htData\x18\n \x01(\x0b\x32\x08.AhtDataH\x00\x12\x1d\n\x08\x61irqData\x18\x0b \x01(\x0b\x32\t.AirQDataH\x00\x12#\n\x0b\x62\x61tteryData\x18\x0c \x01(\x0b\x32\x0c.BatteryDataH\x00\x12/\n\x11wheelOdometryData\x18\x0f \x01(\x0b\x32\x12.WheelOdometryDataH\x00\x42\t\n\x07\x63ontent\"2\n\rMessagePacket\x12!\n\x08messages\x18\x01 \x03(\x0b\x32\x08.MessageB\x05\x92?\x02\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEPACKET.fields_by_name['messages']._options = None
  _MESSAGEPACKET.fields_by_name['messages']._serialized_options = b'\222?\002\020\004'
  _PINGPONG._serialized_start=154
  _PINGPONG._serialized_end=192
  _MESSAGE._serialized_start=195
  _MESSAGE._serialized_end=725
  _MESSAGEPACKET._serialized_start=727
  _MESSAGEPACKET._serialized_end=777
# @@protoc_insertion_point(module_scope)
