# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\"~\n\x07ImuData\x12\x0b\n\x03\x61_x\x18\x01 \x01(\x02\x12\x0b\n\x03\x61_y\x18\x02 \x01(\x02\x12\x0b\n\x03\x61_z\x18\x03 \x01(\x02\x12\x0b\n\x03g_x\x18\x04 \x01(\x02\x12\x0b\n\x03g_y\x18\x05 \x01(\x02\x12\x0b\n\x03g_z\x18\x06 \x01(\x02\x12\x0b\n\x03m_x\x18\x07 \x01(\x02\x12\x0b\n\x03m_y\x18\x08 \x01(\x02\x12\x0b\n\x03m_z\x18\t \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMUDATA._serialized_start=13
  _IMUDATA._serialized_end=139
# @@protoc_insertion_point(module_scope)
