# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmotors.proto\"\x1d\n\x0cMotorCommand\x12\r\n\x05speed\x18\x01 \x01(\x02\"d\n\x0bMotorStatus\x12\x15\n\rcurrent_speed\x18\x01 \x01(\x02\x12\x14\n\x0ctarget_speed\x18\x02 \x01(\x02\x12\x11\n\tpid_speed\x18\x03 \x01(\x02\x12\x15\n\rencoder_value\x18\x04 \x01(\x05\".\n\x08MotorPID\x12\n\n\x02kp\x18\x01 \x01(\x02\x12\n\n\x02ki\x18\x02 \x01(\x02\x12\n\n\x02kd\x18\x03 \x01(\x02\"/\n\x0cSpeedCommand\x12\x0e\n\x06linear\x18\x01 \x01(\x02\x12\x0f\n\x07\x61ngular\x18\x02 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motors_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOTORCOMMAND._serialized_start=16
  _MOTORCOMMAND._serialized_end=45
  _MOTORSTATUS._serialized_start=47
  _MOTORSTATUS._serialized_end=147
  _MOTORPID._serialized_start=149
  _MOTORPID._serialized_end=195
  _SPEEDCOMMAND._serialized_start=197
  _SPEEDCOMMAND._serialized_end=244
# @@protoc_insertion_point(module_scope)
